[output]
font = "Computer Modern Math"
format = "SVG"

[syntax.index]
active = true
allow_numbers = true
operators = [ "*", "+", ":" ]

[syntax.form.mark]
mark = [ "<", ">" ]
mark_alt = [ "⟨", "⟩" ]
entry_mark = "|" 

[syntax.persmissions]
allow_enclosings = true
allow_num_idx = true
enclosures = true
allow_alt_values = true
switch_LR_brackets = false
LTR_mode = false

[syntax.form.reentry.RTL]
mark = [ "(", ")", ]
entry_mark = "|-"
flip_mark = "{"

[syntax.operators.LTR]
mark = [ "[", "]", ]
mark_alt = [ "⁅", "⁆" ]
entry_mark = "-|"
flip_mark = "}"

[syntax.symbols]
active = true
quoted_dbl = [ "\"", "\"" ]
quoted_sngl = [ "'", "'" ]

[syntax.symbols.pattern]
obj = '[abcpqrst]'
var = '[xyz]'
struct = '[A-Z]'
meta_obj = '[αβδγεω]'
meta_var = '[ξλμς]'
meta_struct = '[φψ]'

[syntax.helper]
empties = [ '.', '_' ]

[syntax.meta]
sep = [ " ", " " ]
is_equal = "=="
is_not_equal = "!="
negation = "!!"
conjunction = "&&"
implies = "==>"
is_implied = "<=="
disjunction = "!&"

[syntax.note]
comment = [ "?/", "/" ]
